name: 'HuskHomes'
description: 'A powerful, intuitive and flexible teleportation suite'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.huskhomes.BukkitHuskHomes'
version: '${version}'
api-version: 1.16
softdepend:
  - Vault
  - RedisEconomy
  - dynmap
  - BlueMap
  - Plan
libraries:
  - 'io.lettuce:lettuce-core:${lettuce_version}'
  - 'mysql:mysql-connector-java:${mysql_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
  - 'org.apache.commons:commons-text:${commons_text_version}'

commands:
  home:
    usage: /home <name>
  sethome:
    usage: /sethome <name>
  homelist:
    usage: /homelist [page]
    aliases: [homes]
  delhome:
    usage: /delhome <name>
  edithome:
    usage: /edithome <name> [rename|description|relocate|privacy] [args]
  publichome:
    usage: /publichome [<owner_name>.<home_name>]
    aliases:  [phome]
  publichomelist:
    usage: /publichomelist [page]
    aliases:  [phomelist, phomes]
  warp:
    usage: /warp <name>
  setwarp:
    usage: /setwarp <name>
  warplist:
    usage: /warplist [page]
    aliases: [warps]
  delwarp:
    usage: /delwarp <name>
  editwarp:
    usage: /editwarp <name> [rename|description|relocate] [args]
  tp:
    usage: /tp <target> [destination]
    aliases: [tpo]
  tphere:
    usage: /tphere <player>
    aliases: [tpohere]
  tpa:
    usage: /tpa <player>
  tpahere:
    usage: /tpahere <player>
  tpaccept:
    usage: /tpaccept [player]
    aliases: [tpyes]
  tpdecline:
    usage: /tpdecline [player]
    aliases: [tpdeny, tpno]
  rtp:
    usage: /rtp [player]
  tpignore:
    usage: /tpignore
  tpoffline:
    usage: /tpoffline <player>
  tpall:
    usage: /tpall
  tpaall:
    usage: /tpaall
  spawn:
    usage: /spawn
  setspawn:
    usage: /setspawn
  back:
    usage: /back
  huskhomes:
    usage: /huskhomes [about|help|reload|update|migrate]