name: 'HuskHomes'
description: '${description}'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.huskhomes.BukkitHuskHomes'
version: '${version}'
api-version: '1.16'
softdepend:
  - Vault
  - PlaceholderAPI
  - dynmap
  - BlueMap
  - Plan
  - Essentials
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'com.mysql:mysql-connector-j:${mysql_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'

commands:
  home:
    usage: /<command> <name>
  sethome:
    usage: /<command> <name>
  homelist:
    usage: /<command> [player] [page]
    aliases: [ homes ]
  delhome:
    usage: /<command> <name>
  edithome:
    usage: /<command> <name> [rename|description|relocate|privacy] [args]
  phome:
    usage: /<command> [<owner_name>.<home_name>]
    aliases: [ publichome ]
  phomelist:
    usage: /<command> [page]
    aliases: [ publichomelist, phomes ]
  warp:
    usage: /<command> <name>
  setwarp:
    usage: /<command> <name>
  warplist:
    usage: /<command> [page]
    aliases: [ warps ]
  delwarp:
    usage: /<command> <name>
  editwarp:
    usage: /<command> <name> [rename|description|relocate] [args]
  tp:
    usage: /<command> <target> [destination]
    aliases: [ tpo ]
  tphere:
    usage: /<command> <player>
    aliases: [ tpohere ]
  tpa:
    usage: /<command> <player>
  tpahere:
    usage: /<command> <player>
  tpaccept:
    usage: /<command> [player]
    aliases: [ tpyes ]
  tpdecline:
    usage: /<command> [player]
    aliases: [ tpdeny, tpno ]
  rtp:
    usage: /<command> [player] [world]
  tpignore:
    usage: /<command>
  tpoffline:
    usage: /<command> <player>
  tpall:
    usage: /<command>
  tpaall:
    usage: /<command>
  spawn:
    usage: /<command>
  setspawn:
    usage: /<command>
  back:
    usage: /<command>
  huskhomes:
    usage: /<command> [about|help|reload|import|update]