name: 'HuskHomes'
description: '${description}'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.huskhomes.PaperHuskHomes'
loader: 'net.william278.huskhomes.PaperHuskHomesLoader'
version: '${version}'
api-version: 1.19
folia-supported: true
dependencies:
  server:
    Vault:
      load: BEFORE
      required: false
    RedisEconomy:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
    dynmap:
      load: BEFORE
      required: false
    BlueMap:
      load: BEFORE
      required: false
    Plan:
      load: BEFORE
      required: false
    Pl3xMap:
      load: BEFORE
      required: false
    Essentials:
      load: AFTER
      required: false