name: 'HuskHomes'
description: 'A powerful, intuitive and flexible teleportation suite'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.huskhomes.PaperHuskHomes'
loader: 'net.william278.huskhomes.PaperPluginLoader'
version: '${version}'
api-version: 1.19